# Generated by Django 5.2 on 2025-07-11 11:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('security_question', models.CharField(max_length=100, null=True)),
                ('security_answer', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login2',
            fields=[
                ('username', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room_type', models.CharField(default='Regular', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=7, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('classlevel', models.CharField(blank=True, max_length=8, null=True)),
                ('student_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('student_street', models.CharField(blank=True, max_length=100, null=True)),
                ('student_house', models.CharField(blank=True, max_length=50, null=True)),
                ('student_city', models.CharField(blank=True, max_length=50, null=True)),
                ('student_state', models.CharField(blank=True, max_length=50, null=True)),
                ('student_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('parent_street', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_house', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_city', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_state', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=7)),
                ('student_email', models.EmailField(max_length=254)),
                ('classlevel', models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=8)),
                ('student_mobile', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=5)),
                ('student_street', models.CharField(max_length=100)),
                ('student_house', models.CharField(max_length=50)),
                ('student_city', models.CharField(max_length=50)),
                ('student_state', models.CharField(blank=True, max_length=50, null=True)),
                ('student_postal', models.CharField(max_length=10)),
                ('parent_first_name', models.CharField(max_length=100)),
                ('parent_last_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_mobile', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('parent_street', models.CharField(max_length=100)),
                ('parent_house', models.CharField(max_length=50)),
                ('parent_city', models.CharField(max_length=50)),
                ('parent_state', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_postal', models.CharField(max_length=10)),
                ('prev_school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_class_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('tc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('prev_school_street', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_school_house', models.CharField(blank=True, max_length=50, null=True)),
                ('prev_school_city', models.CharField(blank=True, max_length=50, null=True)),
                ('prev_school_state', models.CharField(blank=True, max_length=50, null=True)),
                ('prev_school_postal', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('classlevel', models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReg1',
            fields=[
                ('username', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('classlevel', models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('periods_per_week', models.IntegerField()),
                ('specialized_room', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('username', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='teacher_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='teacher_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('username', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(default='teacher', editable=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri')], max_length=3)),
                ('period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subjects', models.ManyToManyField(to='login.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.question')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.teacherannouncement')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('max_periods_per_day', models.IntegerField(default=6)),
                ('max_periods_per_week', models.IntegerField(default=30)),
                ('class_sections', models.ManyToManyField(to='login.classsection')),
                ('subjects', models.ManyToManyField(to='login.subject')),
                ('unavailable', models.ManyToManyField(blank=True, to='login.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.classsection')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.teacheravailability')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('exam_type', models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment')], max_length=50)),
                ('exam_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.classsection')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.subject')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.teacheravailability', to_field='username')),
            ],
            options={
                'unique_together': {('username', 'subject', 'added_by', 'class_section', 'exam_type', 'exam_date')},
            },
        ),
    ]
