# Generated by Django 5.2 on 2025-08-09 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_studentassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='login.student'),
        ),
    ]
