# Generated by Django 5.2.1 on 2025-07-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='teacher_documents/'),
        ),
        migrations.AlterField(
            model_name='teacherreg',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='teacher_documents/'),
        ),
    ]
