# Generated by Django 5.2.1 on 2025-08-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_assignmentquestion_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherannouncement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='announcements_pdfs/'),
        ),
    ]
