# Generated by Django 5.2.1 on 2025-06-02 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_teacherreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherreg',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='teacher_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'jpg', 'png'])]),
        ),
    ]
