# Generated by Django 5.2 on 2025-06-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_teacherreg_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='security_answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='security_question',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
