# Generated by Django 5.2.1 on 2025-06-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_applreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applreg',
        ),
    ]
