# Generated by Django 5.2.1 on 2025-06-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_delete_applreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('student_email', models.EmailField(max_length=254)),
                ('class_level', models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=2)),
                ('student_mobile', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=5)),
                ('student_street', models.CharField(max_length=100)),
                ('student_house', models.CharField(max_length=50)),
                ('student_city', models.CharField(max_length=50)),
                ('student_state', models.CharField(max_length=50)),
                ('student_postal', models.CharField(max_length=10)),
                ('parent_first_name', models.CharField(max_length=100)),
                ('parent_last_name', models.CharField(max_length=100)),
                ('parent_dob', models.DateField()),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_mobile', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('parent_street', models.CharField(max_length=100)),
                ('parent_house', models.CharField(max_length=50)),
                ('parent_city', models.CharField(max_length=50)),
                ('parent_state', models.CharField(max_length=50)),
                ('parent_postal', models.CharField(max_length=10)),
                ('prev_school_name', models.CharField(max_length=100)),
                ('prev_class_grade', models.CharField(max_length=10)),
                ('tc_number', models.CharField(max_length=50)),
                ('prev_school_street', models.CharField(max_length=100)),
                ('prev_school_house', models.CharField(max_length=50)),
                ('prev_school_city', models.CharField(max_length=50)),
                ('prev_school_state', models.CharField(max_length=50)),
                ('prev_school_postal', models.CharField(max_length=10)),
            ],
        ),
    ]
