# Generated by Django 5.2.1 on 2025-06-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_studentapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentapplication',
            old_name='class_level',
            new_name='classlevel',
        ),
        migrations.RenameField(
            model_name='studentapplication',
            old_name='parent_dob',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='student_dob',
        ),
    ]
