# Generated by Django 5.2.1 on 2025-06-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_rename_class_level_studentapplication_classlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=7),
        ),
    ]
