# Generated by Django 5.2.1 on 2025-06-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_login_security_answer_login_security_question'),
        ('login', '0009_alter_studentapplication_classlevel'),
    ]

    operations = [
    ]
