# Generated by Django 5.2.1 on 2025-06-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_merge_20250606_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='prev_class_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='prev_school_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='prev_school_house',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='prev_school_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='prev_school_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='prev_school_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='prev_school_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='tc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
