# Generated by Django 5.2.1 on 2025-06-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_studentapplication_prev_class_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
