# Generated by Django 5.2.1 on 2025-06-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_studentapplication_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='is_approved',
        ),
    ]
