# Generated by Django 5.2.1 on 2025-06-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_studentapplication_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
    ]
