# Generated by Django 5.2.1 on 2025-06-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_remove_login_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='login',
            name='security_question',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
