# Generated by Django 5.2.1 on 2025-06-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_remove_login_security_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
