# Generated by Django 5.2.1 on 2025-06-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_remove_login_id_alter_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='security_answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='security_question',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
